# Generated by Django 5.2 on 2025-04-12 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
