# Generated by Django 5.2 on 2025-04-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subject_remove_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='section',
            new_name='course',
        ),
    ]
