# Generated by Django 5.2 on 2025-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_section_studentprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(default='A1', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(max_length=30),
        ),
    ]
