# Generated by Django 5.2 on 2025-05-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_exam_description_exam_due_date_exam_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='order',
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Time taken in seconds'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exam_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.examresult'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='quiz_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.quizresult'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(max_length=20),
        ),
    ]
